{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 53,
   "id": "9d82fa56-9aaf-405b-8948-efb057190df4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "DB Password:  ················\n",
      "Wallet Password:  ················\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function Connection.__del__ at 0x7fb9e3e3d820>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/school/opt/anaconda3/lib/python3.9/site-packages/oracledb/connection.py\", line 151, in __del__\n",
      "    self._impl.close(in_del=True)\n",
      "  File \"src/oracledb/impl/thin/connection.pyx\", line 307, in oracledb.thin_impl.ThinConnImpl.close\n",
      "  File \"src/oracledb/impl/thin/protocol.pyx\", line 86, in oracledb.thin_impl.Protocol._close\n",
      "  File \"src/oracledb/impl/thin/protocol.pyx\", line 121, in oracledb.thin_impl.Protocol._close\n",
      "  File \"src/oracledb/impl/thin/protocol.pyx\", line 298, in oracledb.thin_impl.Protocol._final_close\n",
      "  File \"/Users/school/opt/anaconda3/lib/python3.9/ssl.py\", line 1280, in shutdown\n",
      "    super().shutdown(how)\n",
      "OSError: [Errno 49] Can't assign requested address\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Successfully connected to Oracle Database\n"
     ]
    },
    {
     "ename": "DatabaseError",
     "evalue": "DPY-4011: the database or network closed the connection\n[Errno 32] Broken pipe",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mDatabaseError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[0;32msrc/oracledb/impl/thin/packet.pyx:612\u001b[0m, in \u001b[0;36moracledb.thin_impl.WriteBuffer.end_request\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32msrc/oracledb/impl/thin/packet.pyx:591\u001b[0m, in \u001b[0;36moracledb.thin_impl.WriteBuffer._send_packet\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/oracledb/errors.py:111\u001b[0m, in \u001b[0;36m_raise_err\u001b[0;34m(error_num, context_error_message, cause, **args)\u001b[0m\n\u001b[1;32m    109\u001b[0m     message \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mmessage\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mcontext_error_message\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    110\u001b[0m exc_type \u001b[38;5;241m=\u001b[39m ERR_EXCEPTION_TYPES[error_num \u001b[38;5;241m/\u001b[39m\u001b[38;5;241m/\u001b[39m \u001b[38;5;241m1000\u001b[39m]\n\u001b[0;32m--> 111\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m exc_type(_Error(message)) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mcause\u001b[39;00m\n",
      "\u001b[0;31mDatabaseError\u001b[0m: DPY-4011: the database or network closed the connection\n[Errno 32] Broken pipe"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'oracledb.thin_impl.Protocol._send_marker'\n",
      "Traceback (most recent call last):\n",
      "  File \"src/oracledb/impl/thin/packet.pyx\", line 612, in oracledb.thin_impl.WriteBuffer.end_request\n",
      "  File \"src/oracledb/impl/thin/packet.pyx\", line 591, in oracledb.thin_impl.WriteBuffer._send_packet\n",
      "  File \"/Users/school/opt/anaconda3/lib/python3.9/site-packages/oracledb/errors.py\", line 111, in _raise_err\n",
      "    raise exc_type(_Error(message)) from cause\n",
      "oracledb.exceptions.DatabaseError: DPY-4011: the database or network closed the connection\n",
      "[Errno 32] Broken pipe\n"
     ]
    },
    {
     "ename": "DatabaseError",
     "evalue": "DPY-4011: the database or network closed the connection\n[Errno 32] Broken pipe",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mDatabaseError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[0;32msrc/oracledb/impl/thin/packet.pyx:612\u001b[0m, in \u001b[0;36moracledb.thin_impl.WriteBuffer.end_request\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32msrc/oracledb/impl/thin/packet.pyx:591\u001b[0m, in \u001b[0;36moracledb.thin_impl.WriteBuffer._send_packet\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/oracledb/errors.py:111\u001b[0m, in \u001b[0;36m_raise_err\u001b[0;34m(error_num, context_error_message, cause, **args)\u001b[0m\n\u001b[1;32m    109\u001b[0m     message \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mmessage\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mcontext_error_message\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    110\u001b[0m exc_type \u001b[38;5;241m=\u001b[39m ERR_EXCEPTION_TYPES[error_num \u001b[38;5;241m/\u001b[39m\u001b[38;5;241m/\u001b[39m \u001b[38;5;241m1000\u001b[39m]\n\u001b[0;32m--> 111\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m exc_type(_Error(message)) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mcause\u001b[39;00m\n",
      "\u001b[0;31mDatabaseError\u001b[0m: DPY-4011: the database or network closed the connection\n[Errno 32] Broken pipe"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: 'oracledb.thin_impl.Protocol._send_marker'\n",
      "Traceback (most recent call last):\n",
      "  File \"src/oracledb/impl/thin/packet.pyx\", line 612, in oracledb.thin_impl.WriteBuffer.end_request\n",
      "  File \"src/oracledb/impl/thin/packet.pyx\", line 591, in oracledb.thin_impl.WriteBuffer._send_packet\n",
      "  File \"/Users/school/opt/anaconda3/lib/python3.9/site-packages/oracledb/errors.py\", line 111, in _raise_err\n",
      "    raise exc_type(_Error(message)) from cause\n",
      "oracledb.exceptions.DatabaseError: DPY-4011: the database or network closed the connection\n",
      "[Errno 32] Broken pipe\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "230381085 02/07/2023 09:58:55 PM 6100 W LISBON AV,MKE 7 BATTERY DV Unable to Locate Complainant 43.0692162 -87.98900044999999\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381230 02/07/2023 09:57:58 PM 4054 N 64TH ST,MKE 7 THREAT Advised 43.09127895 -87.9917456248324\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381309 02/07/2023 09:57:53 PM 3008 S 8TH ST,MKE 6 CALL FOR POLICE Advised 42.9898583 -87.9212466958434\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381269 02/07/2023 09:57:34 PM 1766 W LAYTON AV,MKE 6 TRBL W/SUBJ Service in Progress 42.95922231313131 -87.93591145454545\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381317 02/07/2023 09:57:03 PM 2920 N VEL R PHILLIPS AV,MKE 5 ASSIGNMENT Assignment Completed 43.0716444 -87.91517506486014\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381313 02/07/2023 09:53:37 PM 5714 N 39TH ST,MKE 4 SHOTS FIRED Unable to Locate Complainant 43.12182625 -87.96078233072453\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381315 02/07/2023 09:52:06 PM 245 W LINCOLN AV,MKE 2 INVESTIGATION Service in Progress 43.00251845 -87.91368539280907\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381300 02/07/2023 09:50:02 PM 5950 N 64TH ST,MKE 4 SUBJ WITH GUN Assignment Completed 43.1260081 -87.99061331696161\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381312 02/07/2023 09:50:01 PM 1703 W WRIGHT ST,MKE 3 SHOTSPOTTER Unable to Locate Complainant 43.063959800000006 -87.93404300257029\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381286 02/07/2023 09:46:52 PM 5680 N 56TH ST,MKE 4 CALL FOR POLICE Advised 43.12111125 -87.9824838610382\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381311 02/07/2023 09:45:05 PM 3006 S 27TH ST,MKE 6 FOLLOW UP To be Filed 42.9904027 -87.9474948\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381310 02/07/2023 09:43:05 PM S 60TH ST / W OKLAHOMA AV,MKE 6 INVESTIGATION Assignment Completed 42.9791981 -87.9878347\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381304 02/07/2023 09:42:28 PM 1014 S 23RD ST,MKE 2 BATTERY DV Service in Progress 43.0207249 -87.94196967499593\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381299 02/07/2023 09:39:37 PM 1851 N OAKLAND AV,MKE 1 ROBBERY ARMED Assignment Completed 43.05564755 -87.89179040301704\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381305 02/07/2023 09:38:03 PM 2333 N 49TH ST,MKE 3 RETURN STATION Assignment Completed 43.06159395 -87.97547796232692\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381298 02/07/2023 09:37:45 PM 3913 N 36TH ST,MKE 7 CALL FOR POLICE Unable to Locate Complainant 43.08812739814358 -87.95849123451477\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381303 02/07/2023 09:36:37 PM 4715 W VLIET ST,MKE 3 SPECIAL ASSIGN Service in Progress 43.0483895 -87.97304123446565\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381254 02/07/2023 09:35:12 PM 3620 W KILBOURN AV,MKE 3 THREAT Unable to Locate Complainant 43.0418997 -87.95923027542892\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381232 02/07/2023 09:31:17 PM 4846 N 45TH ST,MKE 7 BATTERY Service in Progress 43.1057116 -87.9687629001081\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381296 02/07/2023 09:29:15 PM 2844 N OAKLAND AV,MKE 1 SPECIAL ASSIGN Service in Progress 43.0704567 -87.8877457\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381285 02/07/2023 09:29:01 PM N RICHARDS ST / E WRIGHT ST,MKE 5 TRBL W/SUBJ Unable to Locate Complainant 43.0611176 -87.9078408\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381294 02/07/2023 09:28:05 PM 1328 E ALBION ST,MKE 1 WELFARE CITIZEN Service in Progress 43.0505051 -87.8950903\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381156 02/07/2023 09:25:08 PM 3312 W CENTER ST,MKE 7 STOLEN VEHICLE Service in Progress 43.0675564 -87.9200478\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381281 02/07/2023 09:24:47 PM 7829 W SILVER SPRING DR,MKE 4 WELFARE CITIZEN Assignment Completed 43.1192326 -88.0094604\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381291 02/07/2023 09:22:38 PM 3626 W FOND DU LAC AV,MKE 7 RETURN STATION Assignment Completed 43.07674745 -87.9588381884675\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381264 02/07/2023 09:22:33 PM 1439 S 5TH ST,MKE 2 BATTERY Service in Progress 43.016173800000004 -87.9170843\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381290 02/07/2023 09:22:25 PM 2920 N VEL R PHILLIPS AV,MKE 5 REPORTS To be Filed 43.0716444 -87.91517506486014\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381289 02/07/2023 09:22:20 PM 3626 W FOND DU LAC AV,MKE 7 RETURN STATION Assignment Completed 43.07674745 -87.9588381884675\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381288 02/07/2023 09:22:16 PM 208 E FOUR MILE ROAD, RACINE CITY FOLLOW UP Service in Progress NULL NULL\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381288 02/07/2023 09:22:16 PM 208 E FOUR MILE ROAD, RACINE CITY FOLLOW UP Service in Progress NULL NULL\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381273 02/07/2023 09:21:07 PM 2736 N WEIL ST,MKE 5 WELFARE CITIZEN Unable to Locate Complainant 43.06831425 -87.89884928196338\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381283 02/07/2023 09:18:28 PM 3626 W FOND DU LAC AV,MKE 7 RETURN STATION Assignment Completed 43.07674745 -87.9588381884675\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381146 02/07/2023 09:16:42 PM 2932 W MITCHELL ST,MKE 2 FAMILY TROUBLE Advised 43.0127501 -87.9514267\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381118 02/07/2023 09:16:24 PM 4061 N 54TH ST,MKE 7 ROBBERY ARMED Advised 43.0909702 -87.98130695752965\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381280 02/07/2023 09:16:03 PM 6929 W SILVER SPRING DR,MKE 4 TRBL W/SUBJ Open Investigation 43.1190064 -87.99832293561798\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381217 02/07/2023 09:15:01 PM 1328 E ALBION ST,MKE 1 TRBL W/SUBJ Service in Progress 43.0505051 -87.8950903\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381277 02/07/2023 09:14:34 PM 1800 N COMMERCE ST,MKE 5 PATROL Assignment Completed 43.05344874810848 -87.90792692670237\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381271 02/07/2023 09:13:51 PM 4015 N 41ST ST,MKE 7 CALL FOR POLICE Unable to Locate Complainant 43.09023954576619 -87.96431695150837\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381274 02/07/2023 09:12:00 PM 820 E BRADY ST,MKE 1 FOLLOW UP Assignment Completed 43.0530833 -87.9014797\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381268 02/07/2023 09:11:26 PM 5748 N 36TH ST,MKE 4 ENTRY Advised/Referral 43.1225402 -87.95714262548148\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381272 02/07/2023 09:11:19 PM 710 W CENTER ST,MKE 5 TRAFFIC HAZARD To be Filed 43.0675564 -87.9200478\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381265 02/07/2023 09:10:03 PM 920 W NORTH AV,MKE 3 OVERDOSE Service in Progress 43.0607358 -87.92343982086939\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381166 02/07/2023 09:06:32 PM 2301 N LAKE DR,MKE 1 ANIMAL BITE Unable to Locate Complainant 43.0606381 -87.880563\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381263 02/07/2023 09:06:25 PM 9657 W BEATRICE ST,MKE 4 TRBL W/SUBJ Service in Progress 43.17893085 -88.03187510373064\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381257 02/07/2023 09:06:02 PM 4859 N 54TH ST,MKE 7 VIOL REST ORDER Advised 43.106026549999996 -87.98036687497014\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381260 02/07/2023 09:05:37 PM 2604 W CAPITOL DR,MKE 5 TRBL W/SUBJ Advised 43.0900278 -87.9460803010009\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381266 02/07/2023 09:03:08 PM N 29TH ST / W ATKINSON AV,MKE 5 INVESTIGATION Service in Progress 43.0678298 -87.9498572\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381228 02/07/2023 09:02:08 PM 1337 W LOCUST ST,MKE 5 TRBL W/SUBJ Advised 43.071153236660024 -87.92820854999434\n",
      "Error updating Database: DPY-4011: the database or network closed the connection\n",
      "[Errno 9] Bad file descriptor\n",
      "230381261 02/07/2023 09:00:44 PM 2920 N VEL R PHILLIPS AV,MKE 5 RETURN STATION Assignment Completed 43.0716444 -87.91517506486014\n"
     ]
    },
    {
     "ename": "DatabaseError",
     "evalue": "DPY-4011: the database or network closed the connection\n[Errno 9] Bad file descriptor",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mDatabaseError\u001b[0m                             Traceback (most recent call last)",
      "Input \u001b[0;32mIn [53]\u001b[0m, in \u001b[0;36m<cell line: 78>\u001b[0;34m()\u001b[0m\n\u001b[1;32m    105\u001b[0m         \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mError updating Database:\u001b[39m\u001b[38;5;124m\"\u001b[39m, e)\n\u001b[1;32m    106\u001b[0m         \u001b[38;5;28mprint\u001b[39m(callnumber, date, location, district, nature, status, latitude, longitude)\n\u001b[0;32m--> 108\u001b[0m \u001b[43mconnection\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcommit\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    110\u001b[0m time\u001b[38;5;241m.\u001b[39msleep(\u001b[38;5;241m30\u001b[39m\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m60\u001b[39m)\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/oracledb/connection.py:322\u001b[0m, in \u001b[0;36mConnection.commit\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    318\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m    319\u001b[0m \u001b[38;5;124;03mCommits any pending transactions to the database.\u001b[39;00m\n\u001b[1;32m    320\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m    321\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_verify_connected()\n\u001b[0;32m--> 322\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_impl\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcommit\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32msrc/oracledb/impl/thin/connection.pyx:314\u001b[0m, in \u001b[0;36moracledb.thin_impl.ThinConnImpl.commit\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32msrc/oracledb/impl/thin/protocol.pyx:383\u001b[0m, in \u001b[0;36moracledb.thin_impl.Protocol._process_single_message\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32msrc/oracledb/impl/thin/protocol.pyx:384\u001b[0m, in \u001b[0;36moracledb.thin_impl.Protocol._process_single_message\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32msrc/oracledb/impl/thin/protocol.pyx:344\u001b[0m, in \u001b[0;36moracledb.thin_impl.Protocol._process_message\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32msrc/oracledb/impl/thin/protocol.pyx:321\u001b[0m, in \u001b[0;36moracledb.thin_impl.Protocol._process_message\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32msrc/oracledb/impl/thin/messages.pyx:288\u001b[0m, in \u001b[0;36moracledb.thin_impl.Message.send\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32msrc/oracledb/impl/thin/packet.pyx:612\u001b[0m, in \u001b[0;36moracledb.thin_impl.WriteBuffer.end_request\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32msrc/oracledb/impl/thin/packet.pyx:591\u001b[0m, in \u001b[0;36moracledb.thin_impl.WriteBuffer._send_packet\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/oracledb/errors.py:111\u001b[0m, in \u001b[0;36m_raise_err\u001b[0;34m(error_num, context_error_message, cause, **args)\u001b[0m\n\u001b[1;32m    109\u001b[0m     message \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mmessage\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mcontext_error_message\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    110\u001b[0m exc_type \u001b[38;5;241m=\u001b[39m ERR_EXCEPTION_TYPES[error_num \u001b[38;5;241m/\u001b[39m\u001b[38;5;241m/\u001b[39m \u001b[38;5;241m1000\u001b[39m]\n\u001b[0;32m--> 111\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m exc_type(_Error(message)) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mcause\u001b[39;00m\n",
      "\u001b[0;31mDatabaseError\u001b[0m: DPY-4011: the database or network closed the connection\n[Errno 9] Bad file descriptor"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import time\n",
    "import oracledb\n",
    "import getpass\n",
    "from geopy.geocoders import Nominatim\n",
    "\n",
    "# Connect to database\n",
    "password = getpass.getpass(\"DB Password: \")\n",
    "wallet_password = getpass.getpass(\"Wallet Password: \")\n",
    "connection = oracledb.connect(\n",
    "    user=\"admin\",\n",
    "    password=password,\n",
    "    dsn = \"ltl3y0m4d7of29l1_high\",\n",
    "    config_dir=\"./config\",\n",
    "    wallet_location=\"./config\",\n",
    "    wallet_password=wallet_password)\n",
    "\n",
    "print(\"Successfully connected to Oracle Database\")\n",
    "cursor = connection.cursor()\n",
    "\n",
    "# Define functions for geolocation\n",
    "geolocator = Nominatim(user_agent=\"MU-DS-Capstone\")\n",
    "def fix_address(address):\n",
    "    #Error catching\n",
    "    #Not-string error\n",
    "    address = str(address)\n",
    "    # Remove city\n",
    "    if \",\" in address:\n",
    "        address = address[:address.index(\",\")].strip()\n",
    "    # If intersection, just use first street. TODO: Improve this\n",
    "    if \"/\" in address:\n",
    "        address = address[:address.index(\"/\")].strip()\n",
    "    # Remove NA values\n",
    "    if pd.isna(address):\n",
    "        address = np.nan\n",
    "    # Change block address to just be that address number\n",
    "    address = address.replace(\"-BLK\", \"\")\n",
    "    # Catching the BLVD error, needs to say BLVD not BL\n",
    "    if address.endswith(\"BL\"):\n",
    "        address += \"VD\"\n",
    "    # Catching MLK DR error, use old name\n",
    "    address = address.replace(\"MARTIN L KING JR DR\", \"OLD WORLD THIRD ST\")\n",
    "    # Layton Error\n",
    "    address = address.replace(\"S LAYTON ST\", \"S LAYTON BLVD\")\n",
    "    # Leon Error\n",
    "    address = address.replace(\"LEON TR\", \"LEON TERRACE\")\n",
    "    # Mc Kinley Error\n",
    "    address = address.replace(\"MC KINLEY\", \"MCKINLEY\")\n",
    "    # W Fond Du Lac Error\n",
    "    if \"FOND DU LAC\" in address and \"AV\" not in address:\n",
    "        address = address.replace(\"FOND DU LAC\", \"FOND DU LAC AV\")\n",
    "    # Bluemound road error\n",
    "    address = address.replace(\"BLUE MOUND RD\", \"BLUEMOUND RD\")        \n",
    "    return address + \" MILWAUKEE\"\n",
    "\n",
    "def geocode(address):\n",
    "    try:\n",
    "        geocoded = geolocator.geocode(address)\n",
    "    except Exception as e:\n",
    "        print(\"Error geocoding\", e)\n",
    "    return geocoded\n",
    "\n",
    "def get_gps(geocoded, index):\n",
    "    if geocoded is None:\n",
    "        return np.nan\n",
    "    gps = geocoded[1][index]\n",
    "    if index == 0 and abs(gps - 43.0389) > 1:\n",
    "        return np.nan\n",
    "    elif index == 1 and abs(gps + 87.9065) > 1:\n",
    "        return np.nan  \n",
    "    return geocoded[1][index] \n",
    "\n",
    "# Run indefinitely\n",
    "while True:\n",
    "    # Grab police call log from HTML table\n",
    "    url = 'https://itmdapps.milwaukee.gov/MPDCallData/index.jsp?district=All'\n",
    "    headers = {'User-Agent': 'Marquette Data Science'}\n",
    "    html = requests.get(url, headers=headers).content\n",
    "    df = pd.read_html(html, index_col=0, header=None)[-1]\n",
    "    # Remove multi-index\n",
    "    df.columns = df.columns.droplevel(0)\n",
    "\n",
    "    # Add Latitude and Longitude columns to dataframe\n",
    "    fixed_addresses = df.Location.transform(fix_address)\n",
    "    geocoded_addresses = fixed_addresses.apply(geocode)\n",
    "    df[\"Latitude\"] = geocoded_addresses.apply(get_gps, index=0)\n",
    "    df[\"Longitude\"] = geocoded_addresses.apply(get_gps, index=1)\n",
    "\n",
    "    \"\"\" SEND DATA TO SQL DATABASE \"\"\"\n",
    "    \n",
    "    for callnumber, (date, location, district, nature, status, latitude, longitude) in df.iterrows():\n",
    "        if pd.isna(latitude): latitude = \"NULL\"\n",
    "        if pd.isna(longitude): longitude = \"NULL\"\n",
    "        try:\n",
    "            query = f\"SELECT * FROM CALLS WHERE CALL_NUMBER = '{callnumber}' AND DATE_TIME = '{date}' AND LOCATION = '{location}' \\\n",
    "            AND POLICE_DISTRICT = '{district}' AND NATURE_OF_CALL = 'nature' AND STATUS = 'Service in Progress'\"\n",
    "            response = cursor.execute(query).fetchall()\n",
    "            if response:\n",
    "                continue # SKIP IF ALREADY EXISTS IN DATABASE\n",
    "            query = f\"INSERT INTO CALLS VALUES ('{callnumber}', '{date}', '{location}', '{district}', '{nature}', '{status}', {latitude}, {longitude})\"\n",
    "            cursor.execute(query)\n",
    "        except Exception as e:\n",
    "            print(\"Error updating Database:\", e)\n",
    "            print(callnumber, date, location, district, nature, status, latitude, longitude)\n",
    "\n",
    "    connection.commit()\n",
    "    \n",
    "    time.sleep(30*60) # Sleep for 30 minutes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d1da2532-da90-4261-a898-4e3cfa0eada1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
